### ISSUE TITLE
Buscar juego

### ISSUE THREAD

**Issue by CarlosCordoba96** [PochinkiChallenge/GamesAlgorithms#1]

**Comment by DiegoMolero** [comment]
Hola Carlos,

Me parece muy interesante tu pregunta. Hemos estado investigando mi compañero de lab Carlos y yo, y hemos encontrado una API para el desarrollo de algoritmos que abstrae de la parte de las conexiones del juego para que el programador se centre en la parte del algoritmo principalmente. Creo que es una buena opcion para empezar. Te dejo aqui el enlace para que le eches un vistazo: [http://gym.openai.com/]( http://gym.openai.com/)

Dentro de esta web se pueden ver diferentes enviroments o juegos para el desarrollo de algoritmos. Creo q lo mejor sera empezar con uno simple como este:
![imagen](https://user-images.githubusercontent.com/14870400/46604510-ca52f500-caf6-11e8-8bed-6bba3ecd028b.png)

Tambien, para empezar y comprender como utilizar la API de manera rapida podemos utilizar algún tutorial como este: [https://www.youtube.com/watch?v=3zeg7H6cAJw](https://www.youtube.com/watch?v=3zeg7H6cAJw)

Un saludo.

**Comment by CarlosCordoba96** [comment]
Hola Diego,

Probando la librería que nos ofrecen en la web de OpenAI, en los ejemplos de prueba que nos ofrecen me he dado cuenta que al final de la ejecución de los programas nos mostraba un mensaje de error. Para mitigar este error deberemos poner al final de cada script:
`env.close()`

Un saludo`

**Comment by DiegoMolero** [comment]
Gracias por tu aportación Carlos.

Ya tenemos juego para empezar pues, el[ _CartPole_.
](http://gym.openai.com/envs/CartPole-v1/)
Empieza el juego. 
![imagen](https://user-images.githubusercontent.com/14870400/46636923-4cc0d080-cb5a-11e8-9613-5064db54e0c8.png)
